name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'
      - name: Test with Gradle
        run: ./gradlew clean test -i
  integrationtests-jdk-11-gradle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run integration test - Java 11 + Spring + Gradle + Should Succeed
        run: cd ./integration-tests/java11-gradle-spring-success && ./gradlew clean test -i
        id: java11-gradle-spring-success
      - name: Run integration test - Java 11 + Spring + Gradle + Should Fail
        run: cd ./integration-tests/java11-gradle-spring-fail && ./gradlew clean test -i
        id: java11-gradle-spring-fail
        continue-on-error: true
      - name: Check on failures
        if: steps.java11-gradle-spring-fail.outcome != 'failure'
        run: exit 1
  integrationtests-jdk-17-gradle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run integration test - Java 17 + Spring + Gradle + Should Succeed
        run: cd ./integration-tests/java17-gradle-spring-success && ./gradlew clean test -i
        id: java17-gradle-spring-success
      - name: Run integration test - Java 17 + Spring + Gradle + Should Fail
        run: cd ./integration-tests/java17-gradle-spring-fail && ./gradlew clean test -i
        id: java17-gradle-spring-fail
        continue-on-error: true
      - name: Check on failures
        if: steps.java17-gradle-spring-fail.outcome != 'failure'
        run: exit 1
  integrationtests-jdk-8-gradle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run integration test - Java 8 + Spring + Gradle + Should Succeed
        run: cd ./integration-tests/java8-gradle-spring-success && ./gradlew clean test -i
        id: java8-gradle-spring-success
      - name: Run integration test - Java 8 + Spring + Gradle + Should Fail
        run: cd ./integration-tests/java8-gradle-spring-fail && ./gradlew clean test -i
        id: java8-gradle-spring-fail
        continue-on-error: true
      - name: Check on failures
        if: steps.java8-gradle-spring-fail.outcome != 'failure'
        run: exit 1
  integrationtests-jdk-11-maven:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run integration test - Java 11 + Spring + Maven + Should Succeed
        run: cd ./integration-tests/java11-maven-spring-success && mvn clean install
        id: java11-maven-spring-success
      - name: Run integration test - Java 11 + Spring + Maven + Should Fail
        run: cd ./integration-tests/java11-maven-spring-fail && mvn clean install
        id: java11-maven-spring-fail
        continue-on-error: true
      - name: Check on failures
        if: steps.java11-maven-spring-fail.outcome != 'failure'
        run: exit 1
  integrationtests-jdk-8-maven:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run integration test - Java 8 + Spring + Maven + Should Succeed
        run: cd ./integration-tests/java8-maven-spring-success && mvn clean install
        id: java8-maven-spring-success
      - name: Run integration test - Java 8 + Spring + Maven + Should Fail
        run: cd ./integration-tests/java8-maven-spring-fail && mvn clean install
        id: java8-maven-spring-fail
        continue-on-error: true
      - name: Check on failures
        if: steps.java8-maven-spring-fail.outcome != 'failure'
        run: exit 1